name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore CiscoPortManager/CiscoPortManager.csproj

      - name: Publish self-contained EXE
        run: dotnet publish CiscoPortManager/CiscoPortManager.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CiscoPortManager_EXE
          path: publish/CiscoPortManager.exe
